version: '3.5'
volumes:
  database:
  backend_modules:
  frontend_modules:
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    env_file: .env
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - default
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - backend_modules:/usr/src/app/node_modules
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_modules:/usr/src/app/node_modules
    networks:
      - default
networks:
  default:
